#!/bin/bash

thisfile=$( realpath "$0"  )
thisdir=$( dirname "$thisfile" )
#cd "$thisdir/wz-data/designer"
#export PROGRAM_DATA="$thisdir/wz-data"
~/bin/venv/bin/python "$thisdir/wz/datatable-editor.py" "$@"

